"""
SITA — Interactive Setup Wizard

Polished CLI setup that walks through all configuration steps:
1. Trading mode (paper / live)
2. Exchange selection
3. API keys (optional, for live trading)
4. Watchlist configuration
5. Risk parameters
6. Goal settings
7. Generate .env + goal.yaml + strategy.yaml
"""

import os
import sys
import yaml
from pathlib import Path
from typing import Dict, Optional

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Prompt, Confirm, IntPrompt
    from rich.table import Table
    HAS_RICH = True
except ImportError:
    HAS_RICH = False

from sita.config import (
    BASE_DIR, STATE_DIR, SUPPORTED_EXCHANGES, DEFAULT_WATCHLIST,
)

console = Console() if HAS_RICH else None


def _print(text: str, style: str = ""):
    if console:
        console.print(text, style=style)
    else:
        print(text)


def _prompt(message: str, default=None, password=False, choices=None):
    if HAS_RICH:
        from rich.prompt import Prompt
        return Prompt.ask(message, default=default, password=password, choices=choices)
    else:
        suffix = f" [{default}]" if default else ""
        val = input(f"{message}{suffix}: ").strip()
        return val if val else default


def _confirm(message: str, default=True):
    if HAS_RICH:
        from rich.prompt import Confirm
        return Confirm.ask(message, default=default)
    else:
        suffix = " [Y/n]" if default else " [y/N]"
        val = input(f"{message}{suffix}: ").strip().lower()
        if not val:
            return default
        return val.startswith("y")


def _int_prompt(message: str, default=0):
    if HAS_RICH:
        from rich.prompt import IntPrompt
        return IntPrompt.ask(message, default=default)
    else:
        suffix = f" [{default}]" if default else ""
        val = input(f"{message}{suffix}: ").strip()
        return int(val) if val else default


def _header(title: str):
    if console:
        console.rule(f"[bold cyan]{title}[/bold cyan]")
    else:
        print(f"\n{'='*50}")
        print(f"  {title}")
        print(f"{'='*50}")


def _success(text: str):
    _print(f"  ✓ {text}", style="green")


def _info(text: str):
    _print(f"  ⓘ {text}", style="dim")


def _warn(text: str):
    _print(f"  ⚠ {text}", style="yellow")


def _show_exchange_table():
    """Show pre-configured exchanges in a nice table."""
    if console:
        table = Table(title="Pre-Configured Exchanges", show_header=True, header_style="bold")
        table.add_column("ID", style="cyan")
        table.add_column("Name")
        table.add_column("Testnet", justify="center")
        table.add_column("Type")
        table.add_column("Timeframes")
        for eid, cfg in SUPPORTED_EXCHANGES.items():
            table.add_row(
                eid,
                cfg["name"],
                "✅" if cfg.get("paper_trading") else "❌",
                cfg.get("default_type", "spot"),
                ", ".join(cfg.get("timeframes", [])[:4]) + "...",
            )
        console.print(table)
    else:
        print("\nPre-Configured Exchanges:")
        print(f"{'ID':<12} {'Name':<12} {'Testnet':<10} {'Type':<10}")
        print("-" * 44)
        for eid, cfg in SUPPORTED_EXCHANGES.items():
            print(f"{eid:<12} {cfg['name']:<12} {'yes' if cfg.get('paper_trading') else 'no':<10} {cfg.get('default_type', 'spot'):<10}")


def _show_current_config(env_path: Path):
    """Show current configuration if it exists."""
    if not env_path.exists():
        return
    _info("Existing .env found, current values shown as defaults")


def _load_env(env_path: Path) -> Dict[str, str]:
    """Load existing .env values."""
    vals = {}
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                vals[k.strip()] = v.strip()
    return vals


def _save_env(env_path: Path, vals: Dict[str, str]):
    """Save .env file."""
    lines = [
        "# SITA — Environment Configuration",
        "# Generated by 'sita setup'",
        "#",
        "# SECURITY: This file contains API keys. Never commit it.",
        "",
    ]
    for k, v in vals.items():
        lines.append(f"{k}={v}")
    lines.append("")
    env_path.write_text("\n".join(lines))
    env_path.chmod(0o600)


def _save_yaml(path: Path, data: dict):
    """Save YAML file."""
    with open(path, "w") as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False)
    path.chmod(0o600)


def run_setup():
    """Run the interactive setup wizard."""
    env_path = BASE_DIR / ".env"
    goal_path = STATE_DIR / "goal.yaml"
    strategy_path = STATE_DIR / "strategy.yaml"

    existing = _load_env(env_path)
    _show_current_config(env_path)

    # ═══════════════════════════════════════════════════════════════
    # STEP 1: Welcome
    # ═══════════════════════════════════════════════════════════════
    _header("SITA Setup Wizard")

    if console:
        console.print(Panel.fit(
            "[bold]Welcome to SITA — Self-Improving Trading Agent[/bold]\n\n"
            "This wizard will configure everything you need to start trading.\n"
            "You can always re-run this or edit files manually.",
            title="🔱 SITA v1.0.0 'APEX'",
            border_style="cyan",
        ))
    else:
        print("\nWelcome to SITA — Self-Improving Trading Agent")
        print("This wizard will configure everything you need.\n")

    # ═══════════════════════════════════════════════════════════════
    # STEP 2: Trading Mode
    # ═══════════════════════════════════════════════════════════════
    _header("Step 1/7 — Trading Mode")

    _info("Paper trading uses synthetic/fake data — no real money at risk.")
    _info("Live trading requires API keys and real money. Be careful.")

    mode = _prompt(
        "Trading mode",
        default=existing.get("SITA_TRADING_MODE", "paper"),
        choices=["paper", "live"],
    )
    accept_risk = False
    if mode == "live":
        _warn("LIVE TRADING SELECTED — Real money will be at risk!")
        accept_risk = _confirm("Do you accept full responsibility for any losses?", default=False)
        if not accept_risk:
            _info("Switching to paper trading for safety.")
            mode = "paper"

    _success(f"Trading mode: {mode.upper()}")

    # ═══════════════════════════════════════════════════════════════
    # STEP 3: Exchange Selection
    # ═══════════════════════════════════════════════════════════════
    _header("Step 2/7 — Exchange")

    _show_exchange_table()
    _info("You can add any ccxt-supported exchange later. See docs/EXCHANGES.md")

    exchange = _prompt(
        "Exchange ID",
        default=existing.get("SITA_EXCHANGE", "binance"),
        choices=list(SUPPORTED_EXCHANGES.keys()),
    )
    _success(f"Exchange: {SUPPORTED_EXCHANGES[exchange]['name']} ({exchange})")

    # ═══════════════════════════════════════════════════════════════
    # STEP 4: API Keys
    # ═══════════════════════════════════════════════════════════════
    _header("Step 3/7 — API Keys")

    api_key = existing.get("EXCHANGE_API_KEY", "")
    api_secret = existing.get("EXCHANGE_API_SECRET", "")

    if mode == "paper":
        _info("Paper trading doesn't need API keys (synthetic data used).")
        if _confirm("Add API keys anyway for real data feeds?", default=False):
            api_key = _prompt("API Key", default=api_key if api_key else None)
            api_secret = _prompt("API Secret", default="***" if api_secret else None, password=True)
    else:
        _warn("Live trading requires API credentials.")
        if not api_key:
            api_key = _prompt("API Key", password=True)
            api_secret = _prompt("API Secret", password=True)
        else:
            _success("API keys already configured")
            if _confirm("Update API keys?", default=False):
                api_key = _prompt("API Key", password=True)
                api_secret = _prompt("API Secret", password=True)

    # Optional: Discord notifications
    discord_token = existing.get("DISCORD_TOKEN", "")
    discord_channel = existing.get("DISCORD_CHANNEL_ID", "")
    if _confirm("Enable Discord notifications?", default=bool(discord_token)):
        if not discord_token:
            discord_token = _prompt("Discord Bot Token", password=True)
            discord_channel = _prompt("Channel ID for alerts", default=discord_channel)
        else:
            _success("Discord already configured")
            if _confirm("Update Discord settings?", default=False):
                discord_token = _prompt("Discord Bot Token", password=True)
                discord_channel = _prompt("Channel ID", default=discord_channel)

    # ═══════════════════════════════════════════════════════════════
    # STEP 5: Watchlist
    # ═══════════════════════════════════════════════════════════════
    _header("Step 4/7 — Watchlist")

    _info("Which symbols should SITA monitor and trade?")
    _info(f"Default: {', '.join(DEFAULT_WATCHLIST)}")

    custom_watchlist = _confirm("Customize watchlist?", default=False)
    if custom_watchlist:
        watchlist_str = _prompt(
            "Symbols (comma-separated, e.g. BTC/USDT:USDT, ETH/USDT:USDT)",
            default=", ".join(DEFAULT_WATCHLIST),
        )
        watchlist = [s.strip() for s in watchlist_str.split(",") if s.strip()]
    else:
        watchlist = list(DEFAULT_WATCHLIST)

    _success(f"Watchlist: {', '.join(watchlist)}")

    # ═══════════════════════════════════════════════════════════════
    # STEP 6: Risk Parameters
    # ═══════════════════════════════════════════════════════════════
    _header("Step 5/7 — Risk Parameters")

    _info("Configure how much risk SITA is allowed to take.")

    if mode == "paper":
        max_dd = _prompt("Max drawdown % (e.g. 5 for 5%)", default="5")
        daily_loss = _prompt("Daily loss limit % (e.g. 1.5)", default="1.5")
        weekly_loss = _prompt("Weekly loss limit % (e.g. 3)", default="3")
        risk_per_trade = _prompt("Risk per trade % (e.g. 0.5)", default="0.5")
    else:
        _warn("LIVE MODE — Tight risk limits recommended")
        max_dd = _prompt("Max drawdown %", default=existing.get("MAX_DRAWDOWN", "3"))
        daily_loss = _prompt("Daily loss limit %", existing.get("DAILY_LOSS", "1.0"))
        weekly_loss = _prompt("Weekly loss limit %", existing.get("WEEKLY_LOSS", "2"))
        risk_per_trade = _prompt("Risk per trade %", existing.get("RISK_PER_TRADE", "0.25"))

    initial_balance = _prompt("Initial balance (USDT)", default="10000")
    timeframe = _prompt(
        "Trading timeframe",
        default=existing.get("SITA_TIMEFRAME", "15m"),
        choices=["1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "12h", "1d"],
    )
    loop_interval = _prompt("Loop interval (seconds)", default="30")

    _success(f"Risk: {risk_per_trade}/trade, {daily_loss}/day, {weekly_loss}/week, max DD {max_dd}")

    # ═══════════════════════════════════════════════════════════════
    # STEP 7: Goals
    # ═══════════════════════════════════════════════════════════════
    _header("Step 6/7 — Goals")

    _info("What are SITA's performance targets?")

    target_return = _prompt("Target return (30-day, e.g. 0.05 for 5%)", default="0.05")
    min_sharpe = _prompt("Minimum Sharpe ratio", default="1.5")
    min_winrate = _prompt("Minimum win rate (e.g. 0.45 for 45%)", default="0.45")

    _success(f"Goals: {float(target_return)*100:.1f}/30d, Sharpe ≥ {min_sharpe}, WR ≥ {float(min_winrate)*100:.0f}%")

    # ═══════════════════════════════════════════════════════════════
    # STEP 8: Save Everything
    # ═══════════════════════════════════════════════════════════════
    _header("Step 7/7 — Save Configuration")

    # Build .env
    env_vals = {
        "SITA_EXCHANGE": exchange,
        "SITA_TRADING_MODE": mode,
        "SITA_I_ACCEPT_RISK": str(accept_risk).lower(),
        "SITA_BASE_DIR": str(BASE_DIR),
        "SITA_TIMEFRAME": timeframe,
        "SITA_LOOP_INTERVAL": str(loop_interval),
    }
    if api_key:
        env_vals["EXCHANGE_API_KEY"] = api_key
    if api_secret and api_secret != "***":
        env_vals["EXCHANGE_API_SECRET"] = api_secret
    if discord_token:
        env_vals["DISCORD_TOKEN"] = discord_token
    if discord_channel:
        env_vals["DISCORD_CHANNEL_ID"] = discord_channel

    # Build goal.yaml
    goal_data = {
        "initial_balance": float(initial_balance),
        "target_return_30d": float(target_return),
        "max_drawdown": float(max_dd) / 100,
        "min_sharpe": float(min_sharpe),
        "min_win_rate": float(min_winrate),
        "max_daily_loss_pct": float(daily_loss) / 100,
        "max_weekly_loss_pct": float(weekly_loss) / 100,
    }

    # Build strategy.yaml
    strategy_data = {
        "version": "01",
        "entry": {
            "indicator": "rsi",
            "threshold": 30,
            "direction": "long",
        },
        "stop_loss_pct": 2.0,
        "position_size_r": float(risk_per_trade) / 100,
        "regime": "trending",
    }

    # Confirmation
    if console:
        summary = Table(title="Configuration Summary", show_header=False, border_style="cyan")
        summary.add_column("Setting", style="bold")
        summary.add_column("Value")
        summary.add_row("Mode", mode.upper())
        summary.add_row("Exchange", f"{SUPPORTED_EXCHANGES[exchange]['name']} ({exchange})")
        summary.add_row("Watchlist", ", ".join(watchlist))
        summary.add_row("Timeframe", timeframe)
        summary.add_row("Risk per trade", f"{risk_per_trade}%")
        summary.add_row("Max drawdown", f"{max_dd}%")
        summary.add_row("Initial balance", f"{initial_balance} USDT")
        summary.add_row("API Keys", "Configured" if api_key else "None (paper mode)")
        summary.add_row("Discord", "Enabled" if discord_token else "Disabled")
        console.print(summary)
    else:
        print("\nConfiguration Summary:")
        print(f"  Mode: {mode.upper()}")
        print(f"  Exchange: {exchange}")
        print(f"  Watchlist: {', '.join(watchlist)}")
        print(f"  Risk: {risk_per_trade}/trade, max DD {max_dd}")

    if not _confirm("\nSave this configuration?", default=False):
        _warn("Setup cancelled. No files were changed.")
        return

    # Write files
    _save_env(env_path, env_vals)
    _save_yaml(goal_path, goal_data)
    _save_yaml(strategy_path, strategy_data)

    # ═══════════════════════════════════════════════════════════════
    # DONE
    # ═══════════════════════════════════════════════════════════════
    _header("Setup Complete!")

    _success(f".env saved to {env_path}")
    _success(f"goal.yaml saved to {goal_path}")
    _success(f"strategy.yaml saved to {strategy_path}")

    if console:
        console.print(Panel(
            f"[bold green]SITA is ready to trade![/bold green]\n\n"
            f"Start paper trading:\n"
            f"  [cyan]python3 -m sita run[/cyan]\n\n"
            f"Check status:\n"
            f"  [cyan]python3 -m sita status[/cyan]\n\n"
            f"View dashboard:\n"
            f"  [cyan]python3 -m sita dashboard[/cyan]",
            title="Next Steps",
            border_style="green",
        ))
    else:
        print("\nSITA is ready to trade!")
        print("  Start:   python3 -m sita run")
        print("  Status:  python3 -m sita status")
        print("  Dash:    python3 -m sita dashboard")

    return True
